variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test

build-all:
  stage: build
  script:
    - rm -rf build
    - mkdir -p build && cd build
    - srun -A pc2-mitarbeiter -p fpga --constraint=emul --pty bash
    - cmake -DLOG_FFT_SIZE=6 -DCMAKE_BUILD_TYPE=Release ..
    - make
    - chmod +x bin/fft
  artifacts:
    paths:
      - build/bin/p520_hpc_sg280l/emulation/fft1d_64_nointer/fft1d.aocx
      - build/bin/p520_hpc_sg280l/emulation/fft2d_bram_64_nointer/fft2d_bram.aocx
      - build/bin/p520_hpc_sg280l/emulation/fft2d_ddr_64_nointer/fft2d_ddr.aocx
      - build/bin/p520_hpc_sg280l/emulation/fft3d_ddr_64_nointer/fft3d_ddr.aocx
      - build/bin/p520_hpc_sg280l/emulation/fft3d_bram_64_nointer/fft3d_bram.aocx
      - build/bin/test_fftfpga
      - build/bin/fft

test-all:
  stage: test
  script:
    - cd build/bin/
    - CL_CONFIG_CPU_EMULATE_DEVICES=1 ./test_fftfpga
  dependencies:
    - build-all
